//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPayroll
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAttendance
    {
        public int EmpId { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public Nullable<double> TotalDays { get; set; }
        public Nullable<double> WorkingDays { get; set; }
        public Nullable<double> PresentDays { get; set; }
        public Nullable<double> AbsentDays { get; set; }
        public Nullable<double> LopDays { get; set; }
    }
}
